# Generated by Django 4.1.7 on 2023-03-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=25)),
                ('platform_image', models.ImageField(upload_to='platform_images/')),
                ('platform_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
