# Generated by Django 4.1.7 on 2023-04-08 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=1000)),
                ('developer_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('developer_country', models.CharField(max_length=500)),
                ('developer_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.CharField(choices=[('UR', 'Unrated'), ('EO', 'Everyone'), ('E+', 'Everyone 10+'), ('TE', 'Teen'), ('MA', 'Mature'), ('AO', 'Adults Only')], default='UR', max_length=2)),
                ('description', models.TextField(help_text='Enter a brief description of the game', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='groupproject.developer')),
            ],
            options={
                'ordering': ['title', 'platform', 'release_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The genre(s) of the game.', max_length=25)),
                ('description', models.CharField(blank='True', max_length=500, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=25)),
                ('charset', models.CharField(default='Unknown', help_text='The alphabet used by the language. Currently unused', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=25)),
                ('platform_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('platform_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=1000)),
                ('publisher_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('publisher_country', models.CharField(max_length=500)),
                ('publisher_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comment', models.CharField(help_text='Type in your review here', max_length=5000)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('moderation_message', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupproject.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(related_name='language', to='groupproject.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='language',
            field=models.ManyToManyField(related_name='language', to='groupproject.language'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='groupproject.platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='groupproject.publisher'),
        ),
    ]
