# Generated by Django 4.1.7 on 2023-04-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=1000)),
                ('developer_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('developer_country', models.CharField(max_length=500)),
                ('developer_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The genre(s) of the game.', max_length=25)),
                ('description', models.CharField(blank='True', max_length=500, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=25)),
                ('charset', models.CharField(default='Unknown', help_text='The alphabet used by the language. Currently unused', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=25)),
                ('platform_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('platform_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=1000)),
                ('publisher_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('publisher_country', models.CharField(max_length=500)),
                ('publisher_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.CharField(choices=[('UR', 'Unrated'), ('EO', 'Everyone'), ('E+', 'Everyone 10+'), ('TE', 'Teen'), ('MA', 'Mature'), ('AO', 'Adults Only')], default='UR', max_length=2)),
                ('description', models.TextField(help_text='Enter a brief description of the game', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='groupproject.developer')),
                ('genre', models.ManyToManyField(related_name='language', to='groupproject.genre')),
                ('language', models.ManyToManyField(related_name='language', to='groupproject.language')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='groupproject.platform')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='groupproject.publisher')),
            ],
            options={
                'ordering': ['title', 'platform', 'release_date'],
            },
        ),
    ]
