# Generated by Django 4.1.7 on 2023-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_onprobation',
            field=models.BooleanField(default=False, help_text='Designates whether this user in on probation for innapropriate conduct.', verbose_name='probation status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='moderation_message',
            field=models.CharField(blank=True, help_text='Explanation of why the user has been put on probation or banned.', max_length=1000, null=True),
        ),
    ]
