# Generated by Django 4.1.7 on 2023-04-16 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='A descriptive headline for your review', max_length=255)),
                ('comment', models.CharField(help_text='Type in your review here', max_length=5000)),
                ('created', models.TimeField(auto_now_add=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('moderation_message', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupproject.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aeeb48b4-6d9b-44f8-81d5-18c1c8bd7461'), primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('OTH', 'This review is being reported for another reason.'), ('DOX', 'This review contains identifying personal information of the reviewer or someone else.'), ('OFF', 'This review is not about the game.'), ('INN', 'This review contains innapropriate language or content.')], default='INN', max_length=3)),
                ('moderation_note', models.CharField(help_text='If you selected other, please tell us why.', max_length=5000)),
                ('moderation_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewertools.review')),
                ('moderation_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
