# Generated by Django 4.1.7 on 2023-05-12 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviewertools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewticket',
            name='ticket_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviewticket',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f0fda8d-e0d0-41a7-8d54-dbb8092036ce'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewticket',
            name='reason',
            field=models.CharField(choices=[('OFF', 'This review is not about the game.'), ('OTH', 'This review is being reported for another reason.'), ('DOX', 'This review contains identifying personal information of the reviewer or someone else.'), ('INN', 'This review contains innapropriate language or content.')], default='INN', max_length=3),
        ),
    ]
