# Generated by Django 4.1.7 on 2023-05-12 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviewertools', '0002_reviewticket_ticket_open_alter_reviewticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewticket',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f7e2e07-7946-4b5f-acc0-33891a26c814'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewticket',
            name='reason',
            field=models.CharField(choices=[('OTH', 'This review is being reported for another reason.'), ('OFF', 'This review is not about the game.'), ('INN', 'This review contains innapropriate language or content.'), ('DOX', 'This review contains identifying personal information of the reviewer or someone else.')], default='INN', max_length=3),
        ),
    ]
