# Generated by Selenium IDE
import json
import time
import unittest

from django.test import TestCase
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class unittest_TestLogin(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def test_ll(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1936, 1056)
    time.sleep(1)
    self.driver.find_element(By.ID, "search-input").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "search-input").send_keys("drag")
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Dragon Age: Inquisition (PS5, 2014)").click()
    time.sleep(1)
    element = self.driver.find_element(By.LINK_TEXT, "Dragon Age: Inquisition (PS5, 2014)")
    time.sleep(1)
    actions = ActionChains(self.driver)
    time.sleep(1)
    actions.move_to_element(element).perform()
    time.sleep(1)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    time.sleep(1)
    actions = ActionChains(self.driver)
    time.sleep(1)
    #actions.move_to_element(element, 0, 0).perform()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#review_link > .btn").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Write a Review").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "searchbox").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "searchbox").send_keys("dragon")
    time.sleep(1)
    self.driver.find_element(By.ID, "searchbox").send_keys(Keys.ENTER)
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Dragon Age: Inquisition").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".mb3").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "search-input").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "search-input").send_keys("dragon")
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Dragon Age: Inquisition (PS5, 2014)").click()
    time.sleep(1)
    element = self.driver.find_element(By.LINK_TEXT, "Dragon Age: Inquisition (PS5, 2014)")
    time.sleep(1)
    actions = ActionChains(self.driver)
    time.sleep(1)
    actions.move_to_element(element).perform()
    time.sleep(1)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    time.sleep(1)
    actions = ActionChains(self.driver)
    time.sleep(1)
    #actions.move_to_element(element, 0, 0).perform()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#edit_link > .btn").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "searchbox").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "searchbox").send_keys("dragon")
    time.sleep(1)
    self.driver.find_element(By.ID, "searchbox").send_keys(Keys.ENTER)
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "BioWare").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Register").click()
  

if __name__ == '__main__':
    unittest.main()
