# Generated by Selenium IDE
import json
import time
import unittest

from django.test import TestCase
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class unittest_TestLogin(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def test_ll(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1936, 1056)
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_username").send_keys("kfritts")
    time.sleep(1)
    self.driver.find_element(By.ID, "id_password").send_keys("Pepper321")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "userDropdown").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "View Profile").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_first_name").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_first_name").send_keys("Kather")
    time.sleep(1)
    self.driver.find_element(By.ID, "id_last_name").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_last_name").send_keys("Frit")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(11)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "userDropdown").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "View Profile").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_first_name").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_first_name").send_keys("Katherine")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_last_name").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_last_name").send_keys("Fritts")
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "this form").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "userDropdown").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Manage Profile").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_first_name").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_first_name").send_keys("Katherine")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_last_name").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "id_last_name").send_keys("Fritts")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(11)").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "userDropdown").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "View Profile").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Dragon Age: Inquisition").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "userDropdown").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "View Profile").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "userDropdown").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  

if __name__ == '__main__':
    unittest.main()